import axios from 'axios';

class FacebookService {
  constructor() {
    this.GRAPH_URL = `https://graph.facebook.com/${process.env.FB_API_VERSION || 'v25.0'}`;
    this.appId = process.env.FB_APP_ID;
    this.appSecret = process.env.FB_APP_SECRET;
  }

  /**
   * Exchanges a short-lived token generated by the client Facebook SDK
   * for a long-lived user access token.
   */
  async exchangeForLongLivedToken(shortLivedToken) {
    if (!this.appId || !this.appSecret) {
      throw new Error('Server is missing FB_APP_ID or FB_APP_SECRET environment variables');
    }

    try {
      const response = await axios.get(`${this.GRAPH_URL}/oauth/access_token`, {
        params: {
          grant_type: 'fb_exchange_token',
          client_id: this.appId,
          client_secret: this.appSecret,
          fb_exchange_token: shortLivedToken,
        },
      });
      return response.data;
    } catch (error) {
      console.error('Error exchanging token:', error.response?.data || error.message);
      throw error;
    }
  }

  /**
   * Basic Graph API generic GET request wrapper.
   */
  async get(endpoint, accessToken, params = {}) {
    try {
      const response = await axios.get(`${this.GRAPH_URL}${endpoint}`, {
        params: { ...params, access_token: accessToken },
      });
      return response.data;
    } catch (error) {
      this.handleGraphError(error);
    }
  }

  /**
   * Basic Graph API generic DELETE request wrapper.
   */
  async delete(endpoint, accessToken, params = {}) {
    try {
      const response = await axios.delete(`${this.GRAPH_URL}${endpoint}`, {
        params: { ...params, access_token: accessToken },
      });
      return response.data;
    } catch (error) {
      this.handleGraphError(error);
    }
  }

  /**
   * Analyzes Graph API errors and throws standard mapped errors.
   */
  handleGraphError(error) {
    console.error('[Graph API Error]', error.response?.data || error.message);
    const fbError = error.response?.data?.error;
    if (fbError) {
      // Create a mapped error object for the frontend to consume easily
      const mappedError = new Error(fbError.message);
      mappedError.code = fbError.code;
      mappedError.type = fbError.type;
      
      // Error code 190 = Token expired/invalid
      if (fbError.code === 190) {
        mappedError.isAuthError = true;
      }
      throw mappedError;
    }
    throw error;
  }
}

export default new FacebookService();
